### ISSUE TITLE
How to apply to my own task? The A matrix is hard to represent

### ISSUE THREAD

**Issue by universewill** [wyhuai/DDNM#4]
How to apply to my own task? The A matrix is hard to represent

For example, if the task is demoire or derain, how to do that with ddnm?

**Comment by wyhuai** [comment]
These tasks seems difficult for DDNM... For DDNM, The operator A need to be linear and explicitly given, or at least you need to give a linear approximation. What about estimating a mask with transparency for deraining? I am not sure.

**Comment by lxxcontinue** [comment]
If we already estimated the mask for deraining, how do we get the corresponding pseudo-inverse？

**Comment by wyhuai** [comment]
> If we already estimated the mask for deraining, and the mask is hadamard product at the pixel level, how do we get the corresponding pseudo-inverse？

The pseudo-inverse satisfies $\mathbf{A}\mathbf{A}^{\dagger}\mathbf{A}=\mathbf{A}$ or $\mathbf{A}\mathbf{A}^{\dagger}=\mathbf{I}$. Since the mask operation is pixel-wise, we can consider each pixel independently. Say one mask pixel element is $a$, its pseudo-inverse element can be $1/a$, since $a * 1/a = 1$; Say one mask pixel element is $0$, its pseudo-inverse element can be $0$, since $0 * 0 * 0 = 0$. You may refer to Section 3.2 of our paper for examples.

**Comment by lxxcontinue** [comment]
The mask pixel element is $a$ and pseudo-inverse element is $1/a$ which satisfies $AA^†A ≡ A$ and $AA^† ≡ I$, but it will cause $A^†A ≡ I$. So $\hat{x}_{0|t}=A^†y+(I-A^†A)x$ is going to be equal to $A^†y$, this will result in $x$ having no effect on the final restored image $\hat{x}$.

**Comment by wyhuai** [comment]
> The mask pixel element is a and pseudo-inverse element is 1/a which satisfies AA†A≡A and AA†≡I, but it will cause A†A≡I. So x^0|t=A†y+(I−A†A)x is going to be equal to A†y, this will result in x having no effect on the final restored image x^.

Yes, if $1/a$ is the true degradation, then it is fully reversible (null space does not exist).

**Comment by lxxcontinue** [comment]
Thank you for your reply. A fully reversible degradation operator has no meaning for sampling in DDNM. The derain or low-light enhancement tasks may be difficult to complete.
Thank you again for your answer.
